#pragma once

enum class UserFields
{
	FIELD_NUMB_STARTING_STREETS,
	FIELD_STARTING_DISTANCE_MIN,
	FIELD_STARTING_DISTANCE_MAX,
	FIELD_MAX_STREETS,
	FIELD_STREET_DISTANCE_MIN,
	FIELD_STREET_DISTANCE_MAX,
	FIELD_DIVISION_PERCENT_CHANCE,
	FIELD_GROWING_COLOR,
	FIELD_FINISHED_COLOR,
	FIELD_STREET_DIVISION_ANGLE_MIN,
	FIELD_STREET_DIVISION_ANGLE_MAX,
	FIELD_MIN_DISTANCE_BETWEEN_DIVISIONS,
	FIELD_NONE
};